export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  ADD_TO_CART: "ADD_TO_CART",
  ADD_ONE_ITEM_TO_CART: "ADD_ONE_ITEM_TO_CART",
  REMOVE_ITEM_CART: "REMOVE_ITEM_CART",
  CLEAR_CART: "CLEAR_CART",
};
